services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'academus'
      MYSQL_USER: 'academus'
      MYSQL_PASSWORD: 'academus@123'
      MYSQL_ROOT_PASSWORD: 'academus@123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
